### ISSUE TITLE
@Inject not working

### ISSUE THREAD

**Issue by wh81752** [quarkiverse/quarkiverse-cxf#99]
Hello quarkiverse-cxf,

I'm trying to use "@Inject" in my WebService like illustrated below. 

It is not working for reasons unkown to me:

- @Inject injects nothing
- @PostConstruct is invoked at "Startup-Time", i.e. WebService is always application scoped.

Would you mind to clarify? Especially also how to get my webservice in request scope (performance is not an issue in my case).
 
```
@WebService(endpointInterface = "org.acme.cxf.FruitWebService")
public class FruitWebServiceImpl implements FruitWebService {

   @Inject
   FruitStore store;    // some backend service, contains Apple, Pineapple ..

   @PostConstruct
   void postConstruct() {
      System.out.println("store: " + store);    // output is:  "store: null"
   }
   ..
}
```

Thanks in advance.

**Comment by dufoli** [comment]
have you try on master ? because it has been fixed few days ago with #52

**Comment by wh81752** [comment]
Sorry, I missed #52 as this appears to be my current problem (@Inject not working). Whether it also tackles the second problem (@ApplicationScoped vs @RequestScope) is unclear to me). I'm going to give master a try now and come back.

**Comment by wh81752** [comment]
**Negative**, still not working with 0.4.0-SNAPSHOT (today's master).

Creating bean dynamically like 
```
CDI.current().select(FruitStore.class).get();
```
works fine.

I double checked that 0.4.0-SNAPSHOT is really installed / used by wiping all quarkus-cxf*.jar from Maven's local repo. 

Btw, is there a quick way to check that my installed quarkus-cxf is really used? I'm bit surprised to see that
```
mvn quarkus:list-extensions | fgrep -i cxf
```
list no result whatsoever...

**Comment by dufoli** [comment]
hmm strange. Can you provide a unit test case ?

**Comment by dufoli** [comment]
ok it is fixed and I add a unit test for it and it pass...

**Comment by wh81752** [comment]
I 'm able to confirm that the problem is fixed. Nonetheless, I'm getting a `javax.enterprise.context.ContextNotActiveException` when trying to have my service request scoped:

```
@RequestScoped
@WebService(endpointInterface = "org.acme.cxf.FruitWebService")
public class FruitWebServiceImpl implements FruitWebService {
  // as before
}
```

```
Caused by: javax.enterprise.context.ContextNotActiveException
        at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:40)
        [..]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.jaxws.JAXWSMethodInvoker.performInvocation(JAXWSMethodInvoker.java:66)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        ... 24 more
```

Going to create another issue (with test case) to keep this issue clean.

**Comment by dufoli** [comment]
yes please open a new issue.

**Comment by dufoli** [comment]
web service is not RequestScoped but is created when I initial server on cxf.
https://cxf.apache.org/javadoc/latest/org/apache/cxf/frontend/ServerFactoryBean.html#setServiceBean-java.lang.Object-
So it is a kind of singleton. Why you need requestScoped ?

**Comment by wh81752** [comment]
> Why you need requestScoped ?

See #106.
